name: CI

# Events using 'ON'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Every workflow have one or more jobs
jobs:
  master_change:
    runs-on: ubuntu-latest  # VM
    steps:  
      - uses: actions/checkout@v2 # Src code into VM
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci # does a clean install for CI server
      - run: npm run build
      - run: npm run deploy